### ISSUE TITLE
评测一直Waiting

### ISSUE THREAD

**Issue by gandyli** [syzoj/syzoj#119]
RT，自己搭建的OJ [Link](https://oj.gandyli.xyz) A+B一直评测，syzoj-web端调试输出以下消息：
```
SYZOJ is listening on 127.0.0.1:5283...
{"message":"Judge client /judge#mHUVN6b1mzSF4HuvAAAB connected.","level":"info"}
{"message":"Judge client /judge#mHUVN6b1mzSF4HuvAAAB emitted waitForTask.","level":"warn"}
(node:16513) UnhandledPromiseRejectionWarning: ReplyError: ERR unknown command 'bzpopmax'
    at parseError (/opt/syzoj/web/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/opt/syzoj/web/node_modules/redis-parser/lib/parser.js:303:14)
(node:16513) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16513) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
已经确保daemon和runner服务开启

**Comment by Menci** [comment]
Please upgrade your Redis server to at least version 5.
