### ISSUE TITLE
运行迁移脚本错误

### ISSUE THREAD

**Issue by gandyli** [syzoj/syzoj#125]
RT，提示：
```
query: ALTER TABLE `user_privilege` ADD PRIMARY KEY (`user_id`, `privilege`)
query: ALTER TABLE `user_privilege` DROP PRIMARY KEY
query: ALTER TABLE `user_privilege` ADD PRIMARY KEY (`user_id`)
query failed: ALTER TABLE `user_privilege` ADD PRIMARY KEY (`user_id`)
error: { Error: Duplicate entry '3' for key 'PRIMARY'
    at Packet.asError (/opt/syzoj/web/node_modules/mysql2/lib/packets/packet.js:684:17)
    at Query.execute (/opt/syzoj/web/node_modules/mysql2/lib/commands/command.js:28:26)
    at PoolConnection.handlePacket (/opt/syzoj/web/node_modules/mysql2/lib/connection.js:449:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/opt/syzoj/web/node_modules/mysql2/lib/connection.js:72:12)
    at PacketParser.executeStart (/opt/syzoj/web/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/opt/syzoj/web/node_modules/mysql2/lib/connection.js:79:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlState: '23000',
  sqlMessage: 'Duplicate entry \'3\' for key \'PRIMARY\'' }
query: ROLLBACK
(node:28169) UnhandledPromiseRejectionWarning: QueryFailedError: Duplicate entry '3' for key 'PRIMARY'
    at new QueryFailedError (/opt/syzoj/web/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Query.onResult (/opt/syzoj/web/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:167:45)
    at Query.execute (/opt/syzoj/web/node_modules/mysql2/lib/commands/command.js:30:14)
    at PoolConnection.handlePacket (/opt/syzoj/web/node_modules/mysql2/lib/connection.js:449:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/opt/syzoj/web/node_modules/mysql2/lib/connection.js:72:12)
    at PacketParser.executeStart (/opt/syzoj/web/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/opt/syzoj/web/node_modules/mysql2/lib/connection.js:79:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
(node:28169) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28169) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Menci** [comment]
正常情况下不应该有 ALTER TABLE 的，你是不是没有重新创建数据库？

**Comment by gandyli** [comment]
@Menci 我重新按照说明做了一下，发现题目界面（problems）无法打开，提示：
```
TypeError: /opt/syzoj/web/views/problems.ejs:109
    107|                 <% if (problem.judge_state) { %>
    108|                   <a href="<%= syzoj.utils.makeUrl(['submission', problem.judge_state.id]) %>">
 >> 109|                     <span class="status <%= problem.judge_state.status.toLowerCase().split(' ').join('_') %>">
    110|                       <i class="<%= icon[problem.judge_state.status] || 'remove' %> icon"></i>
    111|                     </span>
    112|                   </a>

Cannot read property 'toLowerCase' of null
    at eval (eval at compile (/opt/syzoj/web/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:539:53)
    at returnedFn (/opt/syzoj/web/node_modules/ejs/lib/ejs.js:653:17)
    at tryHandleCache (/opt/syzoj/web/node_modules/ejs/lib/ejs.js:251:36)
    at View.exports.renderFile [as engine] (/opt/syzoj/web/node_modules/ejs/lib/ejs.js:482:10)
    at View.render (/opt/syzoj/web/node_modules/express/lib/view.js:135:8)
    at tryRender (/opt/syzoj/web/node_modules/express/lib/application.js:640:10)
    at Function.render (/opt/syzoj/web/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/opt/syzoj/web/node_modules/express/lib/response.js:1008:7)
    at app.get (/opt/syzoj/web/modules/problem.js:47:9)
    at <anonymous>
```

**Comment by Menci** [comment]
SELECT COUNT(*) FROM judge_state WHERE status IS NULL

**Comment by gandyli** [comment]
@Menci 请问接下来呢

**Comment by Menci** [comment]
看看结果

**Comment by gandyli** [comment]
+----------+
| COUNT(*) |
+----------+
|       92 |
+----------+
1 row in set (0.000 sec)

**Comment by gandyli** [comment]
```
+----------+
| COUNT(*) |
+----------+
|       92 |
+----------+
1 row in set (0.000 sec)
```

**Comment by Menci** [comment]
整个 judge_state 表一共多少记录啊

**Comment by gandyli** [comment]
@Menci 92

**Comment by Menci** [comment]
建议全部填上 Accepted 然后重测
