### ISSUE TITLE
 网页端首页和比赛页崩溃 提示Error [ERR_IPC_CHANNEL_CLOSED]: channel closed

### ISSUE THREAD

**Issue by pandadtdyy** [syzoj/syzoj#134]
下方为日志
```
May 14 23:33:15 iqzsy-oi-cloud-server node[608]: [session-file-store] Deleting expired sessions
May 14 23:34:55 iqzsy-oi-cloud-server node[608]: query: SELECT `User`.`id` AS `User_id`, `User`.`username` AS `User_username`, `User`.`email` AS `User_email`, `User`.`password` AS `User_password`, `User`.`nickname` AS `User_nickname`, `User`.`nameplate` AS `User_nameplate`, `User`.`information` AS `User_information`, `User`.`ac_num` AS `User_ac_num`, `User`.`submit_num` AS `User_submit_num`, `User`.`is_admin` AS `User_is_admin`, `User`.`is_show` AS `User_is_show`, `User`.`public_email` AS `User_public_email`, `User`.`prefer_formatted_code` AS `User_prefer_formatted_code`, `User`.`sex` AS `User_sex`, `User`.`rating` AS `User_rating`, `User`.`register_time` AS `User_register_time` FROM `user` `User` WHERE `User`.`is_show` = ? ORDER BY ac_num desc LIMIT 20 -- PARAMETERS: [true]
May 14 23:34:55 iqzsy-oi-cloud-server node[608]: Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
May 14 23:34:55 iqzsy-oi-cloud-server node[608]:     at ChildProcess.target.send (internal/child_process.js:588:16)
May 14 23:34:55 iqzsy-oi-cloud-server node[608]:     at Object.exports.markdown (/var/syzoj-web/libs/renderer.js:15:13)
May 14 23:34:55 iqzsy-oi-cloud-server node[608]:     at Promise (/var/syzoj-web/utility.js:59:23)
May 14 23:34:55 iqzsy-oi-cloud-server node[608]:     at Promise._execute (/var/syzoj-web/node_modules/bluebird/js/release/debuggability.js:313:9)
May 14 23:34:55 iqzsy-oi-cloud-server node[608]:     at Promise._resolveFromExecutor (/var/syzoj-web/node_modules/bluebird/js/release/promise.js:483:18)
May 14 23:34:55 iqzsy-oi-cloud-server node[608]:     at new Promise (/var/syzoj-web/node_modules/bluebird/js/release/promise.js:79:10)
May 14 23:34:55 iqzsy-oi-cloud-server node[608]:     at Object.markdown (/var/syzoj-web/utility.js:56:12)
May 14 23:34:55 iqzsy-oi-cloud-server node[608]:     at User.<anonymous> (/var/syzoj-web/models-built/user.js:237:58)
May 14 23:34:55 iqzsy-oi-cloud-server node[608]:     at step (/var/syzoj-web/models-built/user.js:54:23)
May 14 23:34:55 iqzsy-oi-cloud-server node[608]:     at Object.next (/var/syzoj-web/models-built/user.js:35:53)
May 14 23:34:55 iqzsy-oi-cloud-server node[608]:     at /var/syzoj-web/models-built/user.js:29:71
May 14 23:34:55 iqzsy-oi-cloud-server node[608]:     at Promise._execute (/var/syzoj-web/node_modules/bluebird/js/release/debuggability.js:313:9)
May 14 23:34:55 iqzsy-oi-cloud-server node[608]:     at Promise._resolveFromExecutor (/var/syzoj-web/node_modules/bluebird/js/release/promise.js:483:18)
May 14 23:34:55 iqzsy-oi-cloud-server node[608]:     at new Promise (/var/syzoj-web/node_modules/bluebird/js/release/promise.js:79:10)
May 14 23:34:55 iqzsy-oi-cloud-server node[608]:     at __awaiter (/var/syzoj-web/models-built/user.js:25:12)
May 14 23:34:55 iqzsy-oi-cloud-server node[608]:     at User.renderInformation (/var/syzoj-web/models-built/user.js:231:16)
May 14 23:34:55 iqzsy-oi-cloud-server node[608]:     at ranklist.forEachAsync (/var/syzoj-web/modules/index.js:16:46)
May 14 23:34:55 iqzsy-oi-cloud-server node[608]:     at Array.map (<anonymous>)
May 14 23:34:55 iqzsy-oi-cloud-server node[608]:     at Array.forEachAsync.Array.mapAsync (/var/syzoj-web/utility.js:2:27)
May 14 23:34:55 iqzsy-oi-cloud-server node[608]:     at app.get (/var/syzoj-web/modules/index.js:16:20)
May 14 23:34:55 iqzsy-oi-cloud-server node[608]:     at <anonymous>
```

**Comment by Menci** [comment]
渲染进程因为 Node.js 默认内存限制太小而崩溃了，主进程就会出这个错误。

解决方法是在启动时加上 `--max-old-space-size=4096`。
