### ISSUE TITLE
上传ZIP数据时出现Type错误

### ISSUE THREAD

**Issue by rsj001** [syzoj/syzoj#142]
TypeError: require(...) is not a constructor
    at Problem.<anonymous> (/opt/syzoj/web/models-built/problem.js:188:49)
    at step (/opt/syzoj/web/models-built/problem.js:54:23)
    at Object.next (/opt/syzoj/web/models-built/problem.js:35:53)
    at /opt/syzoj/web/models-built/problem.js:29:71
    at Promise._execute (/opt/syzoj/web/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/opt/syzoj/web/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/opt/syzoj/web/node_modules/bluebird/js/release/promise.js:79:10)
    at __awaiter (/opt/syzoj/web/models-built/problem.js:25:12)
    at /opt/syzoj/web/models-built/problem.js:183:120
    at /opt/syzoj/web/node_modules/async-lock/lib/index.js:125:12
    at AsyncLock._promiseTry (/opt/syzoj/web/node_modules/async-lock/lib/index.js:249:31)
    at exec (/opt/syzoj/web/node_modules/async-lock/lib/index.js:124:9)
    at AsyncLock.acquire (/opt/syzoj/web/node_modules/async-lock/lib/index.js:140:3)
    at Object.lock (/opt/syzoj/web/utility.js:277:26)
    at Problem.<anonymous> (/opt/syzoj/web/models-built/problem.js:183:62)
    at step (/opt/syzoj/web/models-built/problem.js:54:23)

请问这是怎么回事呢

**Comment by rsj001** [comment]
node版本v10.15.3

**Comment by rsj001** [comment]
重装一遍就ok了
