### ISSUE TITLE
兼容性问题导致执行 yarn 编译失败

### ISSUE THREAD

**Issue by Kewth** [syzoj/syzoj#161]
当 node 更新到 v12 的时候，在 judge-v3 上执行 `yarn` 会报错。

而实测 node v11 是没有问题的。

问题完全可以而且十分容易复现，把 node 升级到 v12 后 yarn 会失败，并且评测会出现无限 compling 卡在编译的情况。  
本人在两台不同的机子上试过了，出现的状况完全相同。

希望问题可以得到妥善解决 ，感谢。

以下是 yarn 的报错信息：

```plain
error /opt/syzoj/judge/node_modules/syspipe: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /opt/syzoj/judge/node_modules/syspipe
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@12.9.1 | linux | x64
gyp info find Python using Python version 2.7.16 found at "/usr/bin/python2"
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/usr/local/share/.config/yarn/global/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/syzoj/judge/node_modules/syspipe/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/share/.config/yarn/global/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/12.9.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/12.9.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/share/.config/yarn/global/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/12.9.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/opt/syzoj/judge/node_modules/syspipe',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/opt/syzoj/judge/node_modules/syspipe/build'
  CXX(target) Release/obj.target/syspipe/pipe.o
In file included from ../pipe.cc:2:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2232:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2232 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
../pipe.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE syspipe(Nan::NAN_METHOD_ARGS_TYPE)’:
../pipe.cc:35:82: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   35 |    obj->Set(Nan::New<String>("read").ToLocalChecked(), Nan::New<Integer>(desc[0]));
      |                                                                                  ^
In file included from /root/.cache/node-gyp/12.9.1/include/node/v8-internal.h:14,
                 from /root/.cache/node-gyp/12.9.1/include/node/v8.h:25,
                 from /root/.cache/node-gyp/12.9.1/include/node/node.h:63,
                 from ../pipe.cc:1:
/root/.cache/node-gyp/12.9.1/include/node/v8.h:3372:22: note: declared here
 3372 |                 bool Set(Local<Value> key, Local<Value> value));
      |                      ^~~
/root/.cache/node-gyp/12.9.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../pipe.cc:36:83: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   36 |    obj->Set(Nan::New<String>("write").ToLocalChecked(), Nan::New<Integer>(desc[1]));
      |                                                                                   ^
In file included from /root/.cache/node-gyp/12.9.1/include/node/v8-internal.h:14,
                 from /root/.cache/node-gyp/12.9.1/include/node/v8.h:25,
                 from /root/.cache/node-gyp/12.9.1/include/node/node.h:63,
                 from ../pipe.cc:1:
/root/.cache/node-gyp/12.9.1/include/node/v8.h:3372:22: note: declared here
 3372 |                 bool Set(Local<Value> key, Local<Value> value));
      |                      ^~~
/root/.cache/node-gyp/12.9.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../pipe.cc: At global scope:
../pipe.cc:40:11: error: variable or field ‘init’ declared void
   40 | void init(Handle<Object> exports) {
      |           ^~~~~~
../pipe.cc:40:11: error: ‘Handle’ was not declared in this scope
../pipe.cc:40:24: error: expected primary-expression before ‘>’ token
   40 | void init(Handle<Object> exports) {
      |                        ^
../pipe.cc:40:26: error: ‘exports’ was not declared in this scope
   40 | void init(Handle<Object> exports) {
      |                          ^~~~~~~
In file included from ../pipe.cc:1:
../pipe.cc:45:22: error: ‘init’ was not declared in this scope; did you mean ‘int’?
   45 | NODE_MODULE(syspipe, init)
      |                      ^~~~
/root/.cache/node-gyp/12.9.1/include/node/node.h:556:36: note: in definition of macro ‘NODE_MODULE_X’
  556 |       (node::addon_register_func) (regfunc),                          \
      |                                    ^~~~~~~
../pipe.cc:45:1: note: in expansion of macro ‘NODE_MODULE’
   45 | NODE_MODULE(syspipe, init)
      | ^~~~~~~~~~~
In file included from /root/.cache/node-gyp/12.9.1/include/node/node.h:63,
                 from ../pipe.cc:1:
/root/.cache/node-gyp/12.9.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/root/.cache/node-gyp/12.9.1/include/node/node_object_wrap.h:84:78:   required from here
/root/.cache/node-gyp/12.9.1/include/node/v8.h:9893:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
 9893 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/12.9.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:65:61:   required from here
/root/.cache/node-gyp/12.9.1/include/node/v8.h:9893:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [syspipe.target.mk:105: Release/obj.target/syspipe/pipe.o] Error 1
make: Leaving directory '/opt/syzoj/judge/node_modules/syspipe/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/share/.config/yarn/global/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.69-1-MANJARO
gyp ERR! command "/usr/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /opt/syzoj/judge/node_modules/syspipe
gyp ERR! node -v v12.9.1
gyp ERR! node-gyp -v v5.0.3
```

**Comment by Kewth** [comment]
两次测试的 node 版本都是 v12.9.1 。

**Comment by Menci** [comment]
确实不兼容 v12

**Comment by masnn** [comment]
Upgrade needed
