### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by gandyli** [syzoj/syzoj#165]
常规题目提交后显示`Compile Error`，附加消息为`A TimeLimitExceeded encountered while compiling your code.`

**Comment by gandyli** [comment]
附：评测机的daemon给出的错误信息：
```
(node:625) UnhandledPromiseRejectionWarning: LockError: Cannot extend lock on resource "compile-src-cpp17cdffb40726008057c6d031f5cf6da1ce71b921353899c11de7993c71006f123c" because the lock has already expired.
     at Redlock.extend (/opt/syzoj/judge/node_modules/redlock/redlock.js:234:25)
     at Lock.extend (/opt/syzoj/judge/node_modules/redlock/redlock.js:66:22)
     at Timeout.setInterval [as _onTimeout] (/opt/syzoj/judge/src/daemon/redis.ts:29:20)
     at ontimeout (timers.js:498:11)
     at tryOnTimeout (timers.js:323:5)
     at Timer.listOnTimeout (timers.js:290:5)
(node:625) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:625) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by gandyli** [comment]
@Menci

**Comment by Menci** [comment]
已知 bug
