### ISSUE TITLE
Runner服务跑不起来

### ISSUE THREAD

**Issue by gfhfhoo** [syzoj/syzoj#177]
● syzoj-judge-runner.service - SYZOJ judge runner service
   Loaded: loaded (/etc/systemd/system/syzoj-judge-runner.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2019-12-07 13:05:15 CST; 8h ago
  Process: 1898 ExecStart=/usr/bin/node /opt/syzoj/judge/lib/runner/index.js -s /opt/syzoj/config/runner-shared.json -i /opt/syzoj/config/runner-instance.json (code=exi
 Main PID: 1898 (code=exited, status=1/FAILURE)

Dec 07 13:05:15 iZ2zefucqy81r4qo6b0kooZ node[1898]:     at Module._compile (module.js:652:30)
Dec 07 13:05:15 iZ2zefucqy81r4qo6b0kooZ node[1898]:     at Object.Module._extensions..js (module.js:663:10)
Dec 07 13:05:15 iZ2zefucqy81r4qo6b0kooZ node[1898]:     at Module.load (module.js:565:32)
Dec 07 13:05:15 iZ2zefucqy81r4qo6b0kooZ node[1898]:     at tryModuleLoad (module.js:505:12)
Dec 07 13:05:15 iZ2zefucqy81r4qo6b0kooZ node[1898]:     at Function.Module._load (module.js:497:3)
Dec 07 13:05:15 iZ2zefucqy81r4qo6b0kooZ node[1898]:     at Module.require (module.js:596:17)
Dec 07 13:05:15 iZ2zefucqy81r4qo6b0kooZ node[1898]:     at require (internal/module.js:11:18)
Dec 07 13:05:15 iZ2zefucqy81r4qo6b0kooZ node[1898]:     at Object.<anonymous> (/opt/syzoj/judge/src/runner/utils.ts:2:1)
Dec 07 13:05:15 iZ2zefucqy81r4qo6b0kooZ systemd[1]: syzoj-judge-runner.service: Main process exited, code=exited, status=1/FAILURE
Dec 07 13:05:15 iZ2zefucqy81r4qo6b0kooZ systemd[1]: syzoj-judge-runner.service: Failed with result 'exit-code'.

**Comment by gfhfhoo** [comment]
注：Ubuntu 18.04 LTS，最新的代码，py 3.6.9  node.js版本10.8.0

**Comment by gfhfhoo** [comment]
@Menci

**Comment by Menci** [comment]
需要更靠上方的一些 log

**Comment by BlahDuckling747** [comment]
同样的log，原因是node版本太高，yarn安装时出错，我是回退版本解决的（逃

**Comment by MX-Qulin** [comment]
grub改成功了吗?

**Comment by FZ-c** [comment]
请问有解决方案吗？我也遇到了一样的问题。 @Menci

**Comment by Menci** [comment]
@FZ-c 发一下详细 log

**Comment by FZ-c** [comment]
![image](https://user-images.githubusercontent.com/26593764/106231325-66571c00-622c-11eb-8401-a39a99f9d9a2.png)
好像是*cgroup_enable=memory swapaccount=1*没生效，但我不知道怎么解决 = =

**Comment by FZ-c** [comment]
同样是18.04 @Menci

**Comment by Menci** [comment]
1. 执行一下 `cat /proc/cmdline` 看看内核参数
2. 把 `/boot/grub/grub.cfg` 贴到 ubuntu paste 上发过来

**Comment by FZ-c** [comment]
内核参数：
BOOT_IMAGE=/boot/vmlinuz-4.15.0-118-generic root=UUID=5ba34c3d-bd14-451d-a7d8-09a64009e3f1 ro net.ifnames=0 biosdevname=0 console=ttyS0,115200 console=tty0 panic=5 intel_idle.max_cstate=1 intel_pstate=disable crashkernel=1800M-64G:160M,64G-:512M
grub.cfg:
https://paste.ubuntu.com/p/3yxXjfctDM/

**Comment by Menci** [comment]
你的 grub.cfg 里没有需要的那两个内核参数，你可能编辑 `/etc/default/grub` 之后忘了 `update-grub`

**Comment by FZ-c** [comment]
`uodate-grub`执行过了的，也有重启。:(

**Comment by FZ-c** [comment]
啊 我突然解决了
指南中写的是在`GRUB_CMDLINE_LINUX_DEFAULT`后面添加`cgroup_enable=memory swapaccount=1`。
刚刚我尝试了在`GRUB_CMDLINE_LINUX`后面也加上了相同的内容，重启后runner服务就起来了。
可能需要更新补充一下指南吧。 @Menci
