### ISSUE TITLE
syzoj-judge 的 systemd 无法正常启动

### ISSUE THREAD

**Issue by Macesuted** [syzoj/syzoj#196]
配置均与 Wiki 中相同。

启动 `systemctl status syzoj-judge-daemon` 时会显示：
```
● syzoj-judge-daemon.service - SYZOJ judge daemon service
   Loaded: loaded (/etc/systemd/system/syzoj-judge-daemon.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-11-06 08:29:53 CST; 2s ago
  Process: 5132 ExecStart=/usr/bin/node /opt/syzoj/judge/lib/daemon/index.js -c /opt/syzoj/config/daemon.json (code=exited, status=1/FAILURE)
 Main PID: 5132 (code=exited, status=1/FAILURE)

Nov 06 08:29:53 VM-0-3-ubuntu node[5132]:     at Module.require (internal/modules/cjs/loader.js:952:19)
Nov 06 08:29:53 VM-0-3-ubuntu node[5132]:     at require (internal/modules/cjs/helpers.js:88:18)
Nov 06 08:29:53 VM-0-3-ubuntu node[5132]:     at Object.<anonymous> (/opt/syzoj/judge/src/daemon/rmq.ts:2:1)
Nov 06 08:29:53 VM-0-3-ubuntu node[5132]:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
Nov 06 08:29:53 VM-0-3-ubuntu node[5132]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Nov 06 08:29:53 VM-0-3-ubuntu node[5132]:     at Module.load (internal/modules/cjs/loader.js:928:32)
Nov 06 08:29:53 VM-0-3-ubuntu node[5132]:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
Nov 06 08:29:53 VM-0-3-ubuntu node[5132]:     at Module.require (internal/modules/cjs/loader.js:952:19)
Nov 06 08:29:53 VM-0-3-ubuntu systemd[1]: syzoj-judge-daemon.service: Main process exited, code=exited, status=1/FAILURE
Nov 06 08:29:53 VM-0-3-ubuntu systemd[1]: syzoj-judge-daemon.service: Failed with result 'exit-code'.
```
但是手动运行 `/usr/bin/node /opt/syzoj/judge/lib/daemon/index.js -c /opt/syzoj/config/daemon.json`，只会报一个 Warning：`(node:5784) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency`，然后正常运行。

**Comment by Macesuted** [comment]
还有运行 `systemctl start syzoj-judge-runner` 时也会报错：
```
● syzoj-judge-runner.service - SYZOJ judge runner service
   Loaded: loaded (/etc/systemd/system/syzoj-judge-runner.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-11-06 08:34:44 CST; 14s ago
  Process: 5983 ExecStart=/usr/bin/node /opt/syzoj/judge/lib/runner/index.js -s /opt/syzoj/config/runner-shared.json -i /opt/syzoj/config/runner-instance.json (code=exited, st
 Main PID: 5983 (code=exited, status=1/FAILURE)

Nov 06 08:34:44 VM-0-3-ubuntu node[5983]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Nov 06 08:34:44 VM-0-3-ubuntu node[5983]:     at Module.load (internal/modules/cjs/loader.js:928:32)
Nov 06 08:34:44 VM-0-3-ubuntu node[5983]:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
Nov 06 08:34:44 VM-0-3-ubuntu node[5983]:     at Module.require (internal/modules/cjs/loader.js:952:19)
Nov 06 08:34:44 VM-0-3-ubuntu node[5983]:     at require (internal/modules/cjs/helpers.js:88:18)
Nov 06 08:34:44 VM-0-3-ubuntu node[5983]:     at Object.<anonymous> (/opt/syzoj/judge/src/runner/utils.ts:2:1)
Nov 06 08:34:44 VM-0-3-ubuntu node[5983]:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
Nov 06 08:34:44 VM-0-3-ubuntu node[5983]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Nov 06 08:34:44 VM-0-3-ubuntu systemd[1]: syzoj-judge-runner.service: Main process exited, code=exited, status=1/FAILURE
Nov 06 08:34:44 VM-0-3-ubuntu systemd[1]: syzoj-judge-runner.service: Failed with result 'exit-code'.
```
但是手动运行 `/usr/bin/node /opt/syzoj/judge/lib/runner/index.js -s /opt/syzoj/config/runner-shared.json -i /opt/syzoj/config/runner-instance.json` 时同样也会报错：
```
Error: The module '/opt/syzoj/judge/node_modules/posix/build/Release/posix.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at load_extension (/opt/syzoj/judge/node_modules/posix/lib/posix/index.js:16:20)
    at Object.<anonymous> (/opt/syzoj/judge/node_modules/posix/lib/posix/index.js:28:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/opt/syzoj/judge/src/runner/utils.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```
无法正常启动。

请问这应该怎么解决。
