### ISSUE TITLE
兼容性问题导致执行 yarn 编译失败

### ISSUE THREAD

**Issue by EndstoneV** [syzoj/syzoj#247]
完全按照文档操作，甚至名字都没改 还是出现错误
```
root@ubuntu:/opt/syzoj/judge# PATH=/opt/syzoj/node10/bin:$PATH yarn
yarn install v1.22.19
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/3] ⠂ posix
[2/3] ⠂ simple-sandbox
error /opt/syzoj/judge/node_modules/posix: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /opt/syzoj/judge/node_modules/posix
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@10.24.1 | linux | x64
gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v10.24.1/node-v10.24.1-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: connect ECONNREFUSED 104.20.22.46:443
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
gyp ERR! System Linux 5.13.0-52-generic
gyp ERR! command "/opt/syzoj/node10/bin/node" "/opt/syzoj/node10/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/syzoj/judge/node_modules/posix
gyp ERR! node -v v10.24.1
gyp ERR! node-gyp -v v5.1.0
```
## 不同于[#158](https://github.com/syzoj/syzoj/issues/158),我的node版本`10.24.1`

**Comment by Menci** [comment]
```
gyp ERR! stack Error: connect ECONNREFUSED 104.20.22.46:443
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
```

报的错误是网不通，检查一下你的网络连接

**Comment by EndstoneV** [comment]
> ```
> gyp ERR! stack Error: connect ECONNREFUSED 104.20.22.46:443
> gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
> ```
> 
> 报的错误是网不通，检查一下你的网络连接

**Comment by EndstoneV** [comment]
我确认网络没问题：这个操作几秒前还从网络拉取了一些文件。

**Comment by Menci** [comment]
手动下载一下 https://nodejs.org/download/release/v10.24.1/node-v10.24.1-headers.tar.gz 试试

**Comment by EndstoneV** [comment]
![image](https://user-images.githubusercontent.com/89293705/177344483-8cf07fe0-47ae-4936-a03b-9516722837a5.png)
这个nodejs.org上不去，我试过了

**Comment by Menci** [comment]
![image](https://user-images.githubusercontent.com/11341955/177344866-f0e9b072-cfc0-4f82-8882-fbf56a17b39c.png)

我能连上，而且 Node.js 的官网的监控也报告网站目前没有问题

**Comment by EndstoneV** [comment]
但是其他的东西都能上去/kk

**Comment by Menci** [comment]
不管是你的问题还是 Node.js 官网的问题，都和 syzoj 无关

我刚刚亲自在世界各地的多个服务器上测试了一下，没有问题，所以我认为是你的网络有问题
