### ISSUE TITLE
安装之后运行出现错误

### ISSUE THREAD

**Issue by StringKe** [syzoj/syzoj#43]
```shell
[root@JDu4e00u53f7 syzoj]# npm start

> syzoj@2.0.0 start /root/syzoj
> node app.js

SYZOJ is listening on 127.0.0.1:5283...
Unhandled rejection SequelizeBaseError: ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes
    at Query.formatError (/root/syzoj/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
    at Query._callback (/root/syzoj/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/root/syzoj/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query.ErrorPacket (/root/syzoj/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/root/syzoj/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/root/syzoj/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/root/syzoj/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/root/syzoj/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)

```

npm install 后没有出现 需要用到的  syzoj.db 无法导入

**Comment by Menci** [comment]
请贴配置文件 config.json
