### ISSUE TITLE
csrf出错怎么解决

### ISSUE THREAD

**Issue by huangzheng2016** [syzoj/syzoj#48]
ForbiddenError: invalid csrf token
    at csrf (/www/wwwroot/syzoj/node_modules/csurf/index.js:112:19)
    at Layer.handle [as handle_request] (/www/wwwroot/syzoj/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/www/wwwroot/syzoj/node_modules/express/lib/router/index.js:317:13)
    at /www/wwwroot/syzoj/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/www/wwwroot/syzoj/node_modules/express/lib/router/index.js:335:12)
    at next (/www/wwwroot/syzoj/node_modules/express/lib/router/index.js:275:10)
    at /www/wwwroot/syzoj/node_modules/express/lib/router/index.js:635:15
    at next (/www/wwwroot/syzoj/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/www/wwwroot/syzoj/node_modules/express/lib/router/index.js:174:3)
    at router (/www/wwwroot/syzoj/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/www/wwwroot/syzoj/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/www/wwwroot/syzoj/node_modules/express/lib/router/index.js:317:13)
    at /www/wwwroot/syzoj/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/www/wwwroot/syzoj/node_modules/express/lib/router/index.js:335:12)
    at next (/www/wwwroot/syzoj/node_modules/express/lib/router/index.js:275:10)
    at app.use (/www/wwwroot/syzoj/app.js:201:7)
    at Layer.handle [as handle_request] (/www/wwwroot/syzoj/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/www/wwwroot/syzoj/node_modules/express/lib/router/index.js:317:13)
    at /www/wwwroot/syzoj/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/www/wwwroot/syzoj/node_modules/express/lib/router/index.js:335:12)
    at next (/www/wwwroot/syzoj/node_modules/express/lib/router/index.js:275:10)
    at app.use (/www/wwwroot/syzoj/app.js:195:7)

**Comment by pandadtdyy** [comment]
浏览器兼容问题 我使用chrome可以完成操作 360全系都不行 可能360在网页发送端做了什么过滤 你换个浏览器试试 建议是使用chrome

**Comment by Menci** [comment]
Fixed in https://github.com/syzoj/syzoj/commit/33efb33474a69e2d27f3c7569feb80bd2f97255e.
