### ISSUE TITLE
Sequelize似乎不能通过MariaDB添加查询JSON类型?

### ISSUE THREAD

**Issue by fearlessxjdx** [syzoj/syzoj#84]
```CAST((`contest`.`ext_info`->>'$."group"') AS DECIMAL) ```似乎是mysql的语法?
MariaDB要用```COLUMN_GET(ext_info, 'group' AS DECIMAL)?```
```bash
Executing (default): SELECT count(*) AS `count` FROM `contest` AS `contest` WHERE CAST((`contest`.`ext_info`->>'$."group"') AS DECIMAL) = 1;
{ SequelizeDatabaseError: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>>'$."group"') AS DECIMAL) = 1' at line 1
    at Query.formatError (/opt/syzoj/web/node_modules/sequelize/lib/dialects/mysql/query.js:263:16)
    at Query.handler [as onResult] (/opt/syzoj/web/node_modules/sequelize/lib/dialects/mysql/query.js:69:23)
    at Query.execute (/opt/syzoj/web/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/opt/syzoj/web/node_modules/mysql2/lib/connection.js:455:32)
    at PacketParser.onPacket (/opt/syzoj/web/node_modules/mysql2/lib/connection.js:73:18)
    at PacketParser.executeStart (/opt/syzoj/web/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/opt/syzoj/web/node_modules/mysql2/lib/connection.js:80:31)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
  name: 'SequelizeDatabaseError',
```

**Comment by fearlessxjdx** [comment]
是不是我哪里配置搞错了啊 求指教

**Comment by fearlessxjdx** [comment]
`app.js`中直接用`"mysql"`作为了`dialect`
`web.json`中未定义`dialect`
`package.json`中没有使用`mariadb package`  
我用了`"mariadb": "2.0.2-rc"` 后没有报错了
![image](https://user-images.githubusercontent.com/17431574/50570856-b1946b80-0dd5-11e9-8c70-55058e5d8d55.png)
是否需要 Pull requests ? 哪个package更兼容我不太清楚

**Comment by Menci** [comment]
请问问题是在进行什么操作时出现的？我最近更新了 Sequelize 到 beta 版本，可能有一些兼容性问题。

**Comment by fearlessxjdx** [comment]
> 请问问题是在进行什么操作时出现的？我最近更新了 Sequelize 到 beta 版本，可能有一些兼容性问题。

我新加了一个JSON字段到contest表，然后进行where查询的时候发生的。
